title: "Mind Racing"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
aux_links:
  "GitHub":
    - "//github.com/danburonline/mind-racing"
aux_links_new_tab: true
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/danburonline/mind-racing"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"
