# Deploy a new version of the docs for MR-Client as soon as there is a push to the main branch
name: "Client – Docs Deployment"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2.3.1

      - name: Authenticate with the GCP Service Account
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_KEY }}
          service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --silent

      - name: Build Storybook
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: workspace @mind-racing/client run build:doc

      - name: Deploy on Google Cloud Storage
        run: gsutil -m rsync -d -c -r auto-docs/mr-client gs://docs.mind.racing
