# Check formatting and lint all Yarn workspaces as soon as there is a new pull request
name: "Client – Docs Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Setup and install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Create a new .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          envkey_AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL_STAGING }}
          envkey_AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          envkey_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          envkey_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          file_name: .env.production

      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --silent

      - name: Format
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: format

      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
